app = "messagerie-entreprise-backend"
primary_region = "cdg"

[build]

[env]
  NODE_ENV = "production"
  PORT = "4000"
  JWT_ACCESS_EXPIRES = "15m"
  JWT_REFRESH_EXPIRES = "7d"
  LOGIN_RATE_LIMIT_MAX = "5"
  LOGIN_RATE_LIMIT_WINDOW_MIN = "15"
  CORS_ORIGIN = "*"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
